### ISSUE TITLE
Pagination for searched data.

### ISSUE THREAD

**Issue by jordan9800** [ghazanfarmir/laravel-companies-house#20]
I am using 
$companies = CompaniesHouse::search()->all('Ebury');
which gives me a total result of 109 and items_per_page = 20, start_index = 0,
How do I fetch the rest of result with pagination in laravel view.
I request for a guidance in order to do so.

**Comment by GhazanfarMir** [comment]
`CompaniesHouse::search()->all()` method accepts three arguments. So you can provide 2nd and 3rd arguments as below to get paginated data.

`CompaniesHouse::search()->all($keyword, $items_per_page, $start_index);`

e.g.

`CompaniesHouse::search()->all($keyword, 20, 20); // shows you page 2`
