### ISSUE TITLE
Add Laravel 6 and 7 support

### ISSUE THREAD

**Issue by matthewnw** [ghazanfarmir/laravel-companies-house#24]
Would it be possible to Laravel 6 support please?

**Comment by GhazanfarMir** [comment]
Package is updated, try upgrading package and let me know if any issues.

`composer update ghazanfarmir/laravel-companies-house`

**Comment by matthewnw** [comment]
@GhazanfarMir Thanks for updating! Unfortunately I can't update yet, is there a particular reason you are requiring PHP 7.3? As Laravel 6 itself is only requiring ^7.2 Would it be possible to downgrade this requirement? As my projects are mostly running on PHP 7.2.

Also instead of just support for ^7.0.6 can it be backwards compatible for Laravel 5,6 & 7 please i.e. "illuminate/support": "^5.8|^6.0|^7.0" OR ">=5.8", as I don't think any of the new changes have affected the package?

Thanks!
