### ISSUE TITLE
Hardcoded Base URI and API Key in Service Provider

### ISSUE THREAD

**Issue by matthewnw** [ghazanfarmir/laravel-companies-house#32]
Hi, just started getting 403 errors on the package when searching. After some digging I noticed that the base uri and api key are hardcoded! Not sure whether this has always been the case or it the hard coded api key was deleted or companies house updated their security but needs to be updated to use config please.

https://github.com/GhazanfarMir/laravel-companies-house/blob/ac9ddbc4b095bd5fbad258e1b8ae683c0541bcd9/src/CompaniesHouseServiceProvider.php#L25

**Comment by GhazanfarMir** [comment]
See https://github.com/GhazanfarMir/laravel-companies-house/pull/31#issuecomment-608398940

**Comment by GhazanfarMir** [comment]
Resolved by merging #31
